version: '3.8'

services:
  redis:
    image: redis:6.2-alpine
    hostname: redis_in_container
    container_name: redis_db
    restart: always
    command:
      - sh
      - -c
      - redis-server --appendonly yes --maxmemory 450000000 --maxmemory-policy volatile-lru
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 15s
      timeout: 15s
      retries: 5
      start_period: 20s
    profiles:
      - redis_only
      - whole_app
    expose:
      - 6379

    networks:
      - twitter_net

  twitter_parser:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    hostname: parser
    container_name: parser
    restart: always
    depends_on:
      - redis
    env_file:
      - .prod.env
    command: uvicorn main:app --workers 1 --host 0.0.0.0 --port 8000
    profiles:
      - whole_app
    networks:
      - default
      - twitter_net
    expose:
      - 8000

  nginx:
    image: nginx:latest
    volumes:
      - ./app/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./app/nginx/configs:/etc/nginx/conf.d:ro
      - ./app/static:/data/static:ro
    depends_on:
      - twitter_parser
    ports:
      - "80:80"
    restart: always
    networks:
      - twitter_net
    profiles:
      - whole_app

networks:
  twitter_net:
    driver: bridge
